compiler:
    - clang
    - gcc

before_script:
  - sudo apt-get --quiet=2 install cmake libfreeimage-dev cppcheck valgrind

env:
  -
  - OMP_NUM_THREADS=1
  - OMP_NUM_THREADS=4

script:
  - cppcheck --error-exitcode=2 .
  - cmake .
  - make check
  - ./memcheck.bash
  - bash -c './perceptualdiff | grep -i openmp'

after_success:
    - ./coveralls.bash

    - sudo pip install --quiet --use-mirrors git+git://github.com/myint/cpp-coveralls.git
    - coveralls --exclude='CMakeFiles'
