before_script:
  - sudo apt-get --quiet=2 install cmake libfreeimage-dev cppcheck clang

env:
  -
  - OMP_NUM_THREADS=1
  - OMP_NUM_THREADS=4
  - CC=clang CXX=clang++

script:
  - cppcheck --error-exitcode=2 .
  - cmake .
  - make
  - ./test/run_tests.bash
