before_script:
  - sudo apt-get --quiet=2 install cmake libfreeimage-dev cppcheck

env:
  -
  - OMP_NUM_THREADS=1
  - OMP_NUM_THREADS=4

script:
  - cppcheck --error-exitcode=2 .
  - cmake .
  - make
  - ./test/run_tests.bash
