before_script:
  - ls '/usr/include/c++/4.5'
  - sudo apt-get --quiet=2 install cmake libfreeimage-dev cppcheck clang

env:
  -
  - OMP_NUM_THREADS=1
  - OMP_NUM_THREADS=4
  - CC=clang CXX=clang++ CMAKE_CXX_FLAGS='-I/usr/include/c++/4.5'

script:
  - cppcheck --error-exitcode=2 .
  - cmake .
  - make VERBOSE=1
  - ./test/run_tests.bash
