before_script:
  - sudo apt-get --quiet=2 install cmake libfreeimage-dev cppcheck clang
  - ls /usr/include/c++

env:
  -
  - OMP_NUM_THREADS=1
  - OMP_NUM_THREADS=4
  - CC=clang CXX=clang++ CPATH="/usr/include/c++/4.5:${CPATH}"

script:
  - cppcheck --error-exitcode=2 .
  - cmake .
  - make VERBOSE=1
  - ./test/run_tests.bash
