compiler:
    - clang
    - gcc

before_script:
  - sudo apt-get --quiet=2 install cmake libfreeimage-dev cppcheck valgrind

env:
  -
  - OMP_NUM_THREADS=1
  - OMP_NUM_THREADS=4

script:
  - cppcheck --error-exitcode=2 .
  - cmake .
  - make check
  - ./memcheck.bash
  - bash -c './perceptualdiff | grep -i openmp'

after_success:
    - ./coveralls.bash

    - sudo pip install --quiet git+git://github.com/myint/cpp-coveralls.git

    # Ignore header files in a stupid way.
    - rm -f *.h

    - coveralls --exclude='CMakeFiles'
